apiVersion: 1

datasources:
  - name: ClickHouse-nginx-analytics
    type: grafana-clickhouse-datasource
    uid: clickhouse-nginx
    url: http://host.docker.internal:8123
    database: nginx_analytics
    user: analytics_user
    password: analytics_password
    isDefault: true
    jsonData:
      defaultDatabase: nginx_analytics
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      queryTimeout: 60
      dialTimeout: 5
    secureJsonData:
      password: analytics_password