version: '3.8'

services:
  # ClickHouse 数据库
  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: nginx-analytics-clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"    # HTTP接口
      - "9000:9000"    # Native接口
    environment:
      CLICKHOUSE_DB: nginx_analytics
      CLICKHOUSE_USER: analytics_user
      CLICKHOUSE_PASSWORD: analytics_password
    volumes:
      - ../data/clickhouse:/var/lib/clickhouse
      - ../logs/clickhouse:/var/log/clickhouse-server
      - ../config/clickhouse:/etc/clickhouse-server/conf.d
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # Grafana 数据可视化
  grafana:
    image: grafana/grafana:10.2.0
    container_name: nginx-analytics-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource
      GF_SERVER_ROOT_URL: http://localhost:3000/
      GF_PATHS_DATA: /var/lib/grafana
      GF_PATHS_LOGS: /var/log/grafana
    volumes:
      - ../data/grafana:/var/lib/grafana
      - ../logs/grafana:/var/log/grafana
      - ../config/grafana:/etc/grafana/provisioning
    user: "472:472"  # grafana用户ID
    depends_on:
      clickhouse:
        condition: service_healthy

  # Redis for Superset
  redis:
    image: redis:7-alpine
    container_name: nginx-analytics-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ../data/redis:/data
      - ../logs/redis:/var/log/redis
    command: >
      redis-server 
      --appendonly yes 
      --requirepass redis_password
      --save 900 1
      --save 300 10
      --save 60 10000
      --logfile /var/log/redis/redis-server.log

  # PostgreSQL for Superset metadata
  postgres:
    image: postgres:13
    container_name: nginx-analytics-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
      - ../logs/postgres:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset -d superset"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Apache Superset
  superset:
    image: apache/superset:latest
    container_name: nginx-analytics-superset
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=nginx_analytics_secret_key_change_in_production
      - DATABASE_HOST=postgres
      - DATABASE_DB=superset
      - DATABASE_USER=superset
      - DATABASE_PASSWORD=superset_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_password
    volumes:
      - ../data/superset:/app/superset_home
      - ../logs/superset:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      clickhouse:
        condition: service_healthy
    command: >
      bash -c "
        pip install clickhouse-connect &&
        superset db upgrade &&
        (superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin123 || echo 'Admin user might already exist') &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "

networks:
  nginx-analytics:
    name: nginx-analytics-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16