services:
  # ClickHouse 数据库
  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: nginx-analytics-clickhouse-core
    restart: unless-stopped
    ports:
      - "8123:8123"    # HTTP接口
      - "9000:9000"    # Native接口
    volumes:
      - ./volumes/clickhouse/data:/var/lib/clickhouse
      - ./volumes/clickhouse/logs:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: nginx_analytics
      CLICKHOUSE_USER: analytics_user
      CLICKHOUSE_PASSWORD: analytics_password
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Grafana 数据可视化
  grafana:
    image: grafana/grafana:10.2.0
    container_name: nginx-analytics-grafana-core
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource
    depends_on:
      - clickhouse

networks:
  default:
    name: nginx-analytics-core
    driver: bridge